name: ESLint, Prettier

on:
  pull:
    branches:
      - '**'

jobs:
  eslint-prettier-typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Prettier write
        run: npm run prettier:write
      - name: Prettier check
        run: npm run prettier:check
      - name: ESLint check
        run: npm run lint
        env:
          CI: true
