name: CI/CD

on:
  push:
    branches:
      - main 
    paths:
      - 'backend/**'
      - 'frontend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'frontend/**'

jobs:
  backend-tests:
    if: contains(github.event.head_commit.message, 'backend') || startsWith(github.event_name, 'pull_request')
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Create .Env
      run: |
        echo "TRAFIKVERKET_API_KEY=${{ secrets.TRAFIKVERKET_API_KEY }}" >> .env
        echo "ATLAS_USERNAME=${{ secrets.ATLAS_USERNAME }}" >> .env
        echo "ATLAS_PASSWORD=${{ secrets.ATLAS_PASSWORD }}" >> .env
        echo "PORT=${{ secrets.PORT }}" >> .env
        echo "ATLAS_URI=${{ secrets.ATLAS_URI }}" >> .env
        
    - name: Install dependencies
      working-directory: ./backend
      run: npm install

    - name: Lint code
      working-directory: ./backend
      run: npx eslint .

    - name: Format code with Prettier
      working-directory: ./backend
      run: npx prettier --check .

    - name: Run tests
      working-directory: ./backend
      run: npm run test

  frontend-tests:
    if: contains(github.event.head_commit.message, 'frontend') || startsWith(github.event_name, 'pull_request')
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      working-directory: ./frontend
      run: npm install

    - name: Lint code
      working-directory: ./frontend
      run: npx eslint .

    - name: Format code with Prettier
      working-directory: ./frontend
      run: npx prettier --check .

    - name: Run E2E tests
      working-directory: ./frontend
      run: npm run test:e2e
